### ISSUE TITLE
Testing infrastructure for new API endpoints

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/covid-public-api-build#30]
- [x] Create a new branch at `feature/internal-endpoints`
- [ ] Setup http source for states, state-info, and us. These are in older commits pointing at our exsting API and can be reused.
- [x] Change Github workflow on that branch to be triggered manually (webhook and schedule actions are only triggered on default branches)
- [x] Change target ref on action to a [test branch in the API repo](https://github.com/COVID19Tracking/covid-public-api)
- [x] Write a [JSON-diff script](https://www.npmjs.com/package/json-diff) and place diffs in the build assets so any differences between the current API and the new test API are highlighted.

**Comment by zachlipton** [comment]
Great! There's no key required for the read-only internal endpoints, at least currently. I'll have URLs for you to test with once we get one more PR finished and merged. 

There are a couple of places where we won't have complete parity on the field list initially, but your plan to diff them will be great to identify outstanding issues before we launch.

**Comment by kevee** [comment]
Sounds good! I just finished the testing and made it part of the CircleCI build steps. Once we have those endpoints testing should be fast.

**Comment by kevee** [comment]
Branch is now building and deploying here:
https://github.com/COVID19Tracking/covid-public-api/tree/test/internal-endpoints
