### ISSUE TITLE
Change date field from integer to ISO date?

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/covid-public-api-build#84]
Also wondering why the 'date' field is provided as an integer, but not in a readily parsable format. Providing a string such as '2020-06-12' or a universal date format such as ISO would be much more helpful to developers. If a date is provided as an integer, it should be milliseconds. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_267dd)

**Comment by kevee** [comment]
This is part of our V2 proposal.
